fapi2: Fix template call sites for GCC 7
The following errors stop hostboot from building with modern GCC:

src/import/hwpf/fapi2/include/buffer.H:710:23: error: invalid
operands of types ‘<unresolved overloaded function type>’ and
‘fapi2::bufferTraits<long unsigned int, unsigned int>::bits_type
{aka unsigned int}’ to binary ‘operator<’
             out.insert<TS, L, SS>(iv_data);
             ~~~~~~~~~~^~~

src/import/hwpf/fapi2/include/buffer.H: In member function
‘fapi2::buffer<T, TT>& fapi2::buffer<T, TT>::flipBit()’:
src/import/hwpf/fapi2/include/buffer.H:316:49: error: expected
primary-expression before ‘)’ token
             iv_data ^= buffer<T>().setBit<B, C>();
                                                 ^
In both cases the call site needs to be prepended with the keyword
'template'. Otherwise the name is assumed to be a non-template (as per
C++ 14.2/4).

Change-Id: I925c35d51787c4f4f232372f0e1299ec2a5cab42
Signed-off-by: Joel Stanley <joel.stanley@au1.ibm.com>
Reviewed-on: http://ralgit01.raleigh.ibm.com/gerrit1/49760
Tested-by: FSP CI Jenkins <fsp-CI-jenkins+hostboot@us.ibm.com>
Tested-by: Jenkins Server <pfd-jenkins+hostboot@us.ibm.com>
Tested-by: HWSV CI <hwsv-ci+hostboot@us.ibm.com>
Tested-by: PPE CI <ppe-ci+hostboot@us.ibm.com>
Tested-by: Hostboot CI <hostboot-ci+hostboot@us.ibm.com>
Reviewed-by: Daniel M. Crowell <dcrowell@us.ibm.com>
Reviewed-by: ANDRE A. MARIN <aamarin@us.ibm.com>
Reviewed-by: Jennifer A. Stofer <stofer@us.ibm.com>